spring:
  application:
    name: proxy-server
server:
  port: 5555
  servlet:
    context-path: /cloud
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul:
  routes:
    product-service: /api/v1/products/**

